[subsection {Changes for version 1}]

This is the first release of [vset PROJECT].
The changes therefore describe the initial features of the system.

[para] In detail:

[list_begin enumerated]
[comment {- - -- --- ----- -------- ------------- ---------------------}]

[enum] [vset PROJECT] requires Tcl 8.5 or higher.
       Tcl 8.4 or less is not supported.

[enum] [vset PROJECT] requires TclOO.

[enum] The project provides several high- and low-level packages for
       the parsing and rendering of logic-less templates as specified
       by Ruby's [package mustache] package.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[list_end]
